paths:
  model: models/model.pt

feature_extraction:
  radius: 2
  size: 2048

data_preprocessing:
  train_proportion: 0.8
  validation_proportion: 0.1
  test_proportion: 0.1

training:
  first_hidden_size: 512
  second_hidden_size: 256
  dropout: 0.3
  learning_rate: 1e-5
  weight_decay: 1e-5
  max_epochs: 1000
  patience: 10
