paths:
  model: models/model_{model_name}.pt

feature_extraction:
  radius: 2
  size: 2048

data_preprocessing:
  train_proportion: 0.8
  validation_proportion: 0.1
  test_proportion: 0.1

training:
  simple_nn:
    first_hidden_size: 512
    second_hidden_size: 256
    dropout: 0.3
    batch_size: 64
    learning_rate: 1e-5
    weight_decay: 1e-5
    max_epochs: 1000
    patience: 10
  chem_berta:
    trainable_layers: 4
    batch_size: 16
    learning_rate: 1e-5
    weight_decay: 1e-5
    max_epochs: 1
    patience: 10
